//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_management
{
    public partial class budget
    {
        protected global::System.Web.UI.WebControls.TextBox txtMonth;
        protected global::System.Web.UI.WebControls.DropDownList ddlCategory;
        protected global::System.Web.UI.WebControls.TextBox txtAmount;
        protected global::System.Web.UI.WebControls.Button btnSave;
        protected global::System.Web.UI.WebControls.Label lblMonthDisplay;
        protected global::System.Web.UI.WebControls.GridView gvBudget;
    }
}
