//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_management
{
    public partial class Home
    {
        protected global::System.Web.UI.WebControls.Panel pnlDashboard;
        protected global::System.Web.UI.WebControls.Label lblMonth;
        protected global::System.Web.UI.WebControls.Label lblIncome;
        protected global::System.Web.UI.WebControls.Label lblExpense;
        protected global::System.Web.UI.WebControls.Label lblBalance;
        protected global::System.Web.UI.WebControls.GridView gvBudget;
        protected global::System.Web.UI.WebControls.GridView gvRecent;
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl headrem;
        protected global::System.Web.UI.WebControls.GridView GridView1;
        protected global::System.Web.UI.WebControls.Literal litCharts;
    }
}
