//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace Finance_management
{


    public partial class Report
    {

        protected global::System.Web.UI.WebControls.TextBox txtfrom;

        protected global::System.Web.UI.WebControls.TextBox txtto;

        protected global::System.Web.UI.WebControls.Button btnSubmit;

        protected global::System.Web.UI.WebControls.Panel pnlResults;

        protected global::System.Web.UI.WebControls.Label lblIncome;

        protected global::System.Web.UI.WebControls.Label lblExpense;

        protected global::System.Web.UI.WebControls.Label lblSavings;

        protected global::System.Web.UI.WebControls.GridView gvIncomeCat;

        protected global::System.Web.UI.WebControls.GridView gvExpenseCat;
        protected global::System.Web.UI.WebControls.Literal litCharts;
    }
}
